Add in config to bump the inotify/epoll max open instances
PLATFORM-906

The exception we received in the logs was:

    Jan 29, 2013 4:54:24 AM org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink
    WARNING: Failed to initialize an accepted socket.
    org.jboss.netty.channel.ChannelException: Failed to create a selector.
            at org.jboss.netty.channel.socket.nio.NioWorker.register(NioWorker.java:105)
            at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink$Boss.registerAcceptedChannel(NioServerSocketPipelineSink.java:279)
            at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink$Boss.run(NioServerSocketPipelineSink.java:246)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
            at java.lang.Thread.run(Thread.java:722)
    Caused by: java.io.IOException: Too many open files
            at sun.nio.ch.IOUtil.makePipe(Native Method)
            at sun.nio.ch.EPollSelectorImpl.<init>(EPollSelectorImpl.java:65)
            at sun.nio.ch.EPollSelectorProvider.openSelector(EPollSelectorProvider.java:36)
            at java.nio.channels.Selector.open(Selector.java:227)
            at org.jboss.netty.channel.socket.nio.NioWorker.register(NioWorker.java:103)
            ... 5 more

Which seems to implicate insufficient file handles (ulimit). However,
ulimit on nebula is set to 100k open files and we were definitely
nowhere near that. A little googling found this:
http://aprilmayjune.org/2009/01/22/hadoop-and-linux-kernel-2627-epoll-limits/
which mentions the epoll (now inotify in linux 3.2.0) limits as a
culprit. Bumping the limit and will add more monitoring.